title: IEEE Smart World Congress 2026
email: vincenzo.barbuto@unical.it
description: >- # this means to ignore newlines until "baseurl:"
  Join us for the 2026 IEEE Smart World Congress in Cosenza, Calabria, Italy September 7-11, 2026
baseurl: ""
url: "https://swc-ieee-2026.github.io/"
author:
  name: "IEEE SWC 2026 Organizing Committee"
  email: vincenzo.barbuto@unical.it
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Assets
sass:
  sass_dir: _sass
  style: compressed